data_path:
  simulation_path: '/Users/diegofiori/Desktop/epfl/master_thesis/Reverse/'
  save_path: '/Users/diegofiori/Desktop/epfl/master_thesis/results/'


inputs:
  n_time_steps: 6
  n_jobs: -1
  resample_period: 1000